
export const LOADING = "LOADING";
export const LOADING_RESET = "LOADING_RESET";

// Auth

export const RESET = "RESET";

export const LOGIN = "LOGIN";
export const LOGIN_DONE = "LOGIN_DONE";

export const REGISTER = "REGISTER";
export const REGISTER_DONE = "REGISTER_DONE";


export const PUT_USER_DATA = "PUT_USER_DATA";

// profile
export const LOAD_MY_PAYMENTS = "LOAD_MY_PAYMENTS"
export const LOAD_MY_PAYMENTS_DONE = "LOAD_MY_PAYMENTS_DONE"

// residents

export const LOAD_RESIDENTS = "LOAD_RESIDENTS"
export const LOAD_RESIDENTS_SUCCESS = "LOAD_RESIDENTS_SUCCESS"
export const LOAD_RESIDENTS_FAILED = "LOAD_RESIDENTS_FAILED"

export const SHOW_MAINTENANCE_MODAL = "SHOW_MAINTENANCE_MODAL"

export const COLLECT_MAINTENANCE = "COLLECT_MAINTENANCE"
export const COLLECT_MAINTENANCE_DONE = "COLLECT_MAINTENANCE_DONE"


// staff

export const LOAD_STAFF = "LOAD_STAFF"
export const LOAD_STAFF_SUCCESS = "LOAD_STAFF_SUCCESS"
export const LOAD_STAFF_FAILED = "LOAD_STAFF_FAILED"

// policies

export const LOAD_POLICIES = "LOAD_POLICIES"
export const LOAD_POLICIES_DONE = "LOAD_POLICIES_DONE"
export const ADD_UPDATE_POLICIES = "ADD_UPDATE_POLICIES"
export const ADD_UPDATE_POLICIES_DONE = "ADD_UPDATE_POLICIES_DONE"


// maintenance

export const LOAD_MAINTENANCE = "LOAD_MAINTENANCE"
export const LOAD_MAINTENANCE_DONE = "LOAD_MAINTENANCE_DONE"

// building

export const CHANGE_MAINTENANCE = "CHANGE_MAINTENANCE"
export const CHANGE_MAINTENANCE_DONE = "CHANGE_MAINTENANCE_DONE"

export const LOAD_EXPENSES = "LOAD_EXPENSES"
export const LOAD_EXPENSES_DONE = "LOAD_EXPENSES_DONE"

export const ADD_EXPENSE = "ADD_EXPENSE"
export const ADD_EXPENSE_DONE = "ADD_EXPENSE_DONE"

export const DELETE_EXPENSE = "DELETE_EXPENSE"
export const DELETE_EXPENSE_DONE = "DELETE_EXPENSE_DONE"

export const EDIT_EXPENSE = "EDIT_EXPENSE"
export const EDIT_EXPENSE_DONE = "EDIT_EXPENSE_DONE"


// export const CHANGE_MAINTENANCE = "CHANGE_MAINTENANCE"
// export const CHANGE_MAINTENANCE_DONE = "CHANGE_MAINTENANCE_DONE"